import { DEFAULT_PALETTE, palettePreloadScript } from '@kwtech/web-ui';
import type { Metadata } from 'next';
import { Caveat, Geist, Geist_Mono, Literata, Shantell_Sans } from 'next/font/google';
import type { ReactNode } from 'react';
import { appBrand } from '@/config/env';
import { Providers } from './providers';
import './globals.css';

/**
 * Self-hosted by next/font at build time, not fetched from Google at runtime:
 * no third-party request on first paint, and no layout shift while a webfont
 * arrives. Exposed as CSS variables so globals.css can hand them to Tailwind's
 * --font-sans / --font-mono.
 */
const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] });

/**
 * The notes app's writing faces (`@kwtech/module-note`, "Fonts"): the module
 * reads these three variables and cannot load a font itself — its React half
 * may not depend on Next. Handwritten (Shantell Sans) is its default.
 *
 * ⚠ `preload: false`. Every page gets the variables, but a face is only
 * DOWNLOADED when something on the page uses it — the notes app. Preloaded,
 * three faces nobody outside notes ever sees would ride along on every first
 * paint. The cost is one visible swap when notes first opens; the lines do not
 * move, because the notebook's line height is fixed rather than measured.
 */
const noteHand = Shantell_Sans({ variable: '--note-font-hand', subsets: ['latin'], preload: false });
const noteScript = Caveat({ variable: '--note-font-script', subsets: ['latin'], preload: false });
const noteSerif = Literata({ variable: '--note-font-serif', subsets: ['latin'], preload: false });

/**
 * `generateMetadata`, not a static `metadata` export.
 *
 * A static export is evaluated when the route is built, so APP_NAME would be
 * baked into the bundle and renaming the product would mean a rebuild. This
 * function runs per request, which is what makes the name a runtime value
 * everywhere rather than only in the drawer.
 */
export function generateMetadata(): Metadata {
  const { name, tagline } = appBrand();
  return { title: name, description: tagline ? `${name} — ${tagline}` : name };
}

/**
 * Applies the stored palette BEFORE the first paint.
 *
 * Generated by @kwtech/web-ui, which owns both the palettes and the rule that
 * one of them must be on <html> before anything renders. See that package's
 * README for why it has to be inline and undeferred — the short version is that
 * an external or deferred script runs after the browser has already painted.
 */
const PALETTE_SCRIPT = palettePreloadScript();

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    /*
     * DEFAULT_PALETTE is rendered by the server so the page is styled without
     * JavaScript at all — nothing in the stylesheet applies until this
     * attribute exists, so its absence is a blank design, not a fallback one.
     * The script below overrides it for anyone who has chosen.
     *
     * suppressHydrationWarning is required, not defensive: both that script and
     * next-themes' write to <html> before React hydrates, so the server's
     * markup and the client's first pass genuinely differ by those attributes.
     * The alternative — waiting for hydration — is the flash this avoids.
     */
    <html
      lang="en"
      data-palette={DEFAULT_PALETTE}
      className={`${geistSans.variable} ${geistMono.variable} ${noteHand.variable} ${noteScript.variable} ${noteSerif.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full">
        {/* biome-ignore lint/security/noDangerouslySetInnerHtml: a build-time constant with no interpolated input; it must be inline to run before the first paint. */}
        <script dangerouslySetInnerHTML={{ __html: PALETTE_SCRIPT }} />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
